progdisc/AwesomeBot

commands/help/topics/javascript
Add event loop/OOP videos to javascript help.
=> Update JavaScript help resources

.codeclimate.yml
Before merging this, install a webhook for Code Climate so it can see subsequent commits: instructions [here](https://docs.codeclimate.com/docs/installing-code-climates-webhook).
Then, merge this inferred .codeclimate.yml with "eslint-3" channel.
=> Create .codeclimate.yml with eslint-3 channel

TheAwesomeBot.js, commands/help/help.js, commands/pro/pro.js, commands/stream/stream.js, commands/uptime/uptime.js, commands/weather/weather.js, package.json
So, we were using outdated versions of eslint plugins. I'm updating them and now we have to fix some new errors:
```
40:57  error  Expected parentheses around arrow function argument having a body with curly braces  arrow-parens
```
```
15:17  error  Calls to require() should use string literals                                        import/no-dynamic-require
21:7   error  Using 'ForOfStatement' is not allowed                                                no-restricted-syntax
84:14  error  Expected 'undefined' and instead saw 'void'                                          no-void
96:19  error  Unexpected mix of '&&' and '||'                                                      no-mixed-operators
96:31  error  Unexpected mix of '&&' and '||' …
```
=> Bump eslint plugins versions and fix new errors

commands/help/topics/codeblock.txt
People seem to be **waaaay** to confused by the angle brackets. Also added a link for the available language names.
=> Change codeblocks help to be more intuitive.

TheAwesomeBot.js
=> Fix this.onDisconnected and this.onError

commands/help/topics/codeblock.txt
It seems people are still having trouble understanding it. Added an example this time.
=> Changed codeblock help (again!)

.travis.yml, TheAwesomeBot.js, package.json, test/test.js
I added a simple test case to serve as a proof-of-concept. It's a bit hack-ish since I just wanted to make sure this was even doable. And turns out it is! :tada:
I had to put a `setInterval` in there to wait for the bot to be ready. I'm accepting suggestions on how to make this more clear (maybe with promises?).
For the tests, I'm using:
- [`tape`][1] as the test harness
- [`tap-summary`][2] to pretty-print the test results
[1]: https://github.com/substack/tape
[2]: https://github.com/zoubin/tap-summary
=> Add simple test as POC

commands/help/topics/cpp.txt
CPlusPlus tutorial is heavily regarded as awful. Changed it for a better recommendation list.
=> Fixed C++ help topic with a good resource

commands/pbf/pbf.js, settings.json
Add functionality similar to XKCD, but for PBF comics instead.
=> Add PBF Comics 

commands/help/topics/python.txt
Why the hell did we put the old version there?! >.>
=> Updated Think Python's link to 2nd ed

commands/help/topics/python.txt
As much as we'd love for everything to be HTTPS, reality is sad and cruel.
=> Fixed link in Python

commands/help/topics/ruby.txt
Add ruby.txt file to the repo.
=> Add ruby help topic

commands/help/topics/java.txt
For beginners, I don't think that the Java 7 documentation is needed to present as a resource anymore. Also added the Helsinki MOOC that's heavily recommended in #java.
=> Added new resource for Java and removed old docs.

commands/pro/proTerms.txt
=> Added new terms angular1/2, angularjs, ngnix, oracle sql, Redis, Apache

commands/pro/pro.js
Updated the 'Pros' channel name to 'Helpers'
=> Changed Pros to Helpers

commands/quickref/quickref.js, commands/quickref/references/dotnet.txt, commands/quickref/references/linux.txt, commands/quickref/references/printf.txt, commands/quickref/references/regex.txt, commands/quickref/references/sqljoin.txt, settings.json
quickref is a command that will have diagrams or things that are commonly forgotten but easily referenced, such as regex or SQL Joins.
=> Added quickref command

commands/xkcd/xkcd.js
Tested with "rust" and "compiling" comics, seems to work great.
=> Fixing XKCD command. Using JSON API and looking for digits in URL

commands/pro/pro.js
I think it would be useful for a user to look up a specific pro in the help directory instead of manually searching. This will do just that...
=> Modifying pro command to accept a mention of any specific pro

commands/help/topics/python.txt
DiLemmA_CS suggested this good resource for learning Django!
=> Add Tango With Django to the python help list

commands/help/topics/go.txt, commands/help/topics/ml.txt
Added resources for Go to support new #go-language channel, fixed the ML resources to indicate that ISL is a free resource.
=> Added Go resources, fixed ML resources.

commands/help/topics/php.txt
A user 'expected more' when he ran our php help command. Well, I'LL GIVE HIM MORE.
=> Update the PHP help file resource list.

commands/help/topics/python.txt
The course called "Problem Solving with Algorithms and Data Structures
using Python" is based on the book by the same name by  Brad Miller and
David Ranum. A good starting point for beginners.
link:  https://runestone.academy/runestone/static/pythonds/index.html
=> Add a free course for Python in bot help command

commands/weather/weather.js
Somebody derped. I think this underps it.
=> Fix "weather in undefined"

commands/weather/weather.js
Addressed on November 26th, 2017.
This should be revisited at a later time.
=> Added a hotfix to change 'Weather in undefined' bug.
